### ISSUE TITLE
Unexpected Error when Downloading Resource Pack

### ISSUE THREAD

**Issue by watermelophent** [ByMartrixx/VTDownloader#1]
When I try to download any resource pack using this mod, it says an unexpected error occured,  In the log, it says: [VT Download/ERROR]: [VTDownloader] Encountered an exception while trying to download the resource pack.
java.io.IOException: Server returned HTTP response code: 403 for URL: https://vanillatweaks.net/download/VanillaTweaks_r612787.zip.

**Comment by ByMartrixx** [comment]
Have you been able to download a pack since the error happened? If not, are you able to download a pack directly from the website (https://vanillatweaks.net/picker/resource-packs/)?

**Comment by ByMartrixx** [comment]
Just tried to download a pack from the mod and worked as expected, no errors. This might have been a temporal problem on the vanilla tweaks server.

**Comment by watermelophent** [comment]
I am able to download directly from vanillatweaks.net.  I just tried through the mod and it had the same issue.

**Comment by watermelophent** [comment]
Is it a mod incompatibility?

**Comment by ByMartrixx** [comment]
It could be, but I doubt it. Can you give me your mod list (with the mod versions)? I might be able to reproduce using the same mods as you.

**Comment by watermelophent** [comment]
Is there a way I can send the mods folder to you?

**Comment by ByMartrixx** [comment]
A screenshot would do

**Comment by watermelophent** [comment]
Can I send it via MediaFire?  I have too many mods to fit in one screenshot

**Comment by ByMartrixx** [comment]
Yes

**Comment by watermelophent** [comment]
https://www.mediafire.com/folder/geash5atwk9wq/mods

**Comment by ByMartrixx** [comment]
Thank you, I'll check in about an hour

**Comment by ByMartrixx** [comment]
Confirmed!
```
[VTDownloader] Encountered an exception while trying to download the resource pack.
java.io.IOException: Server returned HTTP response code: 403 for URL: https://vanillatweaks.net/download/VanillaTweaks_r288147.zip
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1506)
	at io.github.bymartrixx.vtd.gui.VTDScreen.lambda$download$0(VTDScreen.java:114)
	at io.github.bymartrixx.vtd.gui.VTDScreen$$Lambda$3913/561172638.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```
> `at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)`
This may mean that is a problem with NotEnoughCrashes, I'll try to remove it

**Comment by ByMartrixx** [comment]
Tried without NotEnoughCrashes, still doesn't work

**Comment by ByMartrixx** [comment]
I've tried with only VTDownloader and it still doesn't work, also tried with a "fresh" build and the same happens. For some reason, it does work when using it in my development environment.
