### ISSUE TITLE
Mod doesn't check for VT conflicts

### ISSUE THREAD

**Issue by ThoriumTextile** [ByMartrixx/VTDownloader#16]
I.e. I can select "Item Stitching" and "Diminishing Tools", VTD will download the pack without any issues.
However, ingame the conflicts do show up obviously, such as missing/glitched textures.

**Comment by ThoriumTextile** [comment]
Closed. This is on my end. I have no idea how i didn't notice the blatant blue background. Tooltips indicating such conflicts are missing nonetheless.

**Comment by IotaBread** [comment]
Yeah, I could add a warning before downloading if there are conflicts between the selected packs
