### ISSUE TITLE
Interface bug with Recursive resources mod

### ISSUE THREAD

**Issue by voidrinix** [ByMartrixx/VTDownloader#17]
Hello! MC 1.19.2 , Quilt 0.17.6 .
When Recursive resources and VTDownloader installed at the same time there is a bug with buttons like on the screenshot
![изображение](https://user-images.githubusercontent.com/73175330/200670680-b96e66e2-cc66-4384-aebc-b4807d0d07f5.png)

**Comment by IotaBread** [comment]
Where do you think I could place the button? I think making the "Open pack folder" button wider and dividing it in two could be an option (one for vtd, the other to open the folder), but I'm not too convinced by it

**Comment by osfanbuff63** [comment]
> Where do you think I could place the button? I think making the "Open pack folder" button wider and dividing it in two could be an option (one for vtd, the other to open the folder), but I'm not too convinced by it

This is probably the best option, but you could also do that with the Done button I guess. Or try to squeeze it in the middle, but that might be a bit small of a space haha

**Comment by IotaBread** [comment]
Since Recursive Resources isn't compatible with 1.19.3, I can't fix this issue for now. Either way, until its update, you shouldn't be able to find this issue with the latest VTDownloader version

**Comment by ShayBox** [comment]
It seems both are updated to 1.19.3, but there's no button at all now.
![image](https://user-images.githubusercontent.com/9505196/215015172-73ddaf9d-8235-4bd7-b703-301db4bfe064.png)

**Comment by voidrinix** [comment]
> It seems both are updated to 1.19.3, but there's no button at all now.
> ![image](https://user-images.githubusercontent.com/9505196/215015172-73ddaf9d-8235-4bd7-b703-301db4bfe064.png)

Same

**Comment by osfanbuff63** [comment]
There still doesn't seem to be a button at all for me...am I missing it?
![image](https://user-images.githubusercontent.com/91388253/216469152-e796df92-17df-41e4-b474-034068a9ffca.png)

(i do have both installed here)
![image](https://user-images.githubusercontent.com/91388253/216469351-f45c0a33-6698-4c05-8150-a74519959171.png)

**Comment by IotaBread** [comment]
Something must be wrong with the mixin then, I'll see if I can fix it tomorrow

**Comment by enjarai** [comment]
Recursive Resources author here, if there's anything specific I can do on my side to help with compat, be sure to let me know. My mod replaces the vanilla resourcepack screen with a subclassed version, overriding a lot of things, which could very well be the issue here.

**Comment by IotaBread** [comment]
Sorry about the delay, but I was busy during most February. It should be fixed as of `2.0.3`

**Comment by osfanbuff63** [comment]
Can confirm this is fixed in 2.0.3.
![image](https://user-images.githubusercontent.com/91388253/222979576-7a398541-445d-469d-852b-e70b9f78a53f.png)

**Comment by ghost** [comment]
Seems to be back. I'm on 1.21.7 with 2.3.5.
![image](https://files.catbox.moe/0j57ea.png)
