### ISSUE TITLE
[Bug] Some weird Opacity Bug

### ISSUE THREAD

**Issue by ZaneDragonBorn** [ByMartrixx/VTDownloader#2]
![image](https://user-images.githubusercontent.com/68198648/104784810-1457c600-5757-11eb-9c6a-430f46dd1b58.png)
Not just is the menus very bugged but the border is only near the "Done button"

**Comment by ByMartrixx** [comment]
Can you send the texture pack you are using?

**Comment by ZaneDragonBorn** [comment]
![image](https://user-images.githubusercontent.com/68198648/104823734-66adeb00-581a-11eb-8678-977b5bae5484.png)
These are the Resource Packs i'm using. forgot which one changes the background (Might be Unity Dark Edition)

**Comment by ByMartrixx** [comment]
With your pack, is it supposed to have a transparent or a stone background?

**Comment by ZaneDragonBorn** [comment]
It seems to use both. The Panorama in the background and the stone border as the overlay (wasn't an intentional thing but looked nice).

**Comment by ByMartrixx** [comment]
So, the background of the lists should have the panorama, but the top and bottom of the screen a stone background?

**Comment by ZaneDragonBorn** [comment]
yeah

**Comment by ZaneDragonBorn** [comment]
![image](https://user-images.githubusercontent.com/68198648/104824132-5a775d00-581d-11eb-9cf2-758885862656.png)
It would look like this

**Comment by ByMartrixx** [comment]
Can you send me the files? Without them, I won't be able to properly solve the issue

**Comment by ZaneDragonBorn** [comment]
Sure! One sec

**Comment by ZaneDragonBorn** [comment]
[Unity-1.16.X-Dark-0.6.2.zip](https://github.com/ByMartrixx/VTDownloader/files/5825211/Unity-1.16.X-Dark-0.6.2.zip)
This is the dark Theme that should add the border.

and the one that changes the Background should be the Fabric Mod called "Bedrockify"

**Comment by ByMartrixx** [comment]
I'll look into it as soon as possible

**Comment by ZaneDragonBorn** [comment]
Ok so I may be wrong about That resource pack being the issue. it may just be Bedrockify. Doing some more testing

**Comment by ZaneDragonBorn** [comment]
Ok so Bedrockify will change Backgrounds to be a Panorama and Better Vanilla Building is what changed the Vanilla Borders and Backgrounds (Which is below). These are the 2 causes of the bug.
[bettervanillabuildingV2.45.zip](https://github.com/ByMartrixx/VTDownloader/files/5825230/bettervanillabuildingV2.45.zip)

**Comment by ByMartrixx** [comment]
I have found a workaround the issue. If you disable `Bedrockify settings > Other settings... > Panorama Background On All Screens`, the VTDownloader screen will work.
I won't be able to work on the mod from the next week until February, but I plan on fixing this issue with a quick (and cursed) fix on the next release (1.0.3), which I'm currently working on. Once I can work on it, I'm hoping to do a proper fix to this bug.

**Comment by ZaneDragonBorn** [comment]
Ok Great! Thanks

**Comment by IotaBread** [comment]
Just published 1.0.3
