### ISSUE TITLE
Incompatibility Check

### ISSUE THREAD

**Issue by ZbotZero** [ByMartrixx/VTDownloader#23]
It doesn't check for whether 2 features are incompatible
<img width="1423" alt="Screenshot 2023-02-14 at 9 22 57 AM" src="https://user-images.githubusercontent.com/108658879/218811244-b7e41e61-c771-4303-8f34-406d5b79c6ad.png">

I'd like this to be changed so I don't have to remember what's compatible and what's not

**Comment by IotaBread** [comment]
I forgot to check here yesterday - I have to point out that the two packs you show as selected in the screenshot aren't marked as incompatible in the website either. If you select two incompatible packs, like `Dark GUI` and `Transparent GUI`, their highlights should change color, like on the website. If this doesn't happen, please let me know and reopen the issue
