### ISSUE TITLE
Cannot download from Peace and Quiet > Mobs

### ISSUE THREAD

**Issue by bonn2** [ByMartrixx/VTDownloader#24]
I believe it is an issue with VTDownloader not properly handling Vanilla Tweaks sub folders.
Here is a screenshot of the game vs the website
![image](https://user-images.githubusercontent.com/42011672/222911987-513adddf-4579-4ccc-ac70-30d87529b86a.png)
![image](https://user-images.githubusercontent.com/42011672/222912162-700c20f4-d744-4107-b6e4-03967e5aa571.png)
This is also the case with Aesthetic > More Zombies.

**Comment by IotaBread** [comment]
It seems the format for the subcategories is a bit different from the regular ones, so I'll have to make some changes to how entries are displayed to add support for them

**Comment by IotaBread** [comment]
Support for sub categories is now in development! You can find a built jar in the artifacts section of [the latest build action](https://github.com/ByMartrixx/VTDownloader/actions/runs/5482233361), you have to use the `.jar` file without any `-sources` suffix

Do note it's still early into development, so sub categories aren't very different visually from packs, I have to tweak a some things here and there

**Comment by badooga** [comment]
Yeah, I came across this issue myself while testing - in particular, if I had a pack downloaded from the site that has options from a subcategory, not only would I not be able to edit those subcategories, but updating something else and hitting download would remove them from the pack entirely, requiring me to remake it on the site. Definitely excited for when this is fully released.
