### ISSUE TITLE
1.20?

### ISSUE THREAD

**Issue by GeraldTM** [ByMartrixx/VTDownloader#27]
perhaps?..

**Comment by Kyanoxia** [comment]
Perchance?

**Comment by GeraldTM** [comment]
i might make this a pr, i have time to try anyway

**Comment by IotaBread** [comment]
If you can make a pr it'd be very welcome, if not, I can do the update during the next few days

**Comment by GeraldTM** [comment]
Yeah... life said no to free time lol.

**Comment by JACKKY04** [comment]
1.20.1 update?

**Comment by IotaBread** [comment]
I'm working on it, I don't have a lot of free time, but it should be done by wednesday
