### ISSUE TITLE
Causes a crash on startup

### ISSUE THREAD

**Issue by spencersolberg** [ByMartrixx/VTDownloader#4]
I'm using MultiMC on Linux, with just the Fabric Loader and VTDownloader installed, and I'm unable to launch the game (1.16.5). I've attached a log file, hopefully that will help!
[minecraft log.txt](https://github.com/ByMartrixx/VTDownloader/files/6039429/minecraft.log.txt)

**Comment by IotaBread** [comment]
Could you provide me the mod jar that you are using and where did you download it from? I already had this issue reported on the curseforge page, saying that the Modrinth version crashes, I thought I had fixed this, but seems like I didn't. Does the version appear as `${version}` on MultiMC? Also, thanks for attaching the logs!

**Comment by spencersolberg** [comment]
Github won't let me upload a jar, but here's a Mediafire link: [vt-downloader-1.0.3-sources(2).jar](http://www.mediafire.com/file/ej7yyp7wf11yda4/vt-downloader-1.0.3-sources(2).jar/file). It's got (2) at the end because I've downloaded it a few times now, I believe from Modrinth each time. It is showing up as `${version}`: 
![image](https://user-images.githubusercontent.com/46253322/109095065-a9e45f00-76e0-11eb-9937-8dcd4b75823d.png)

The version from CurseForge seems to load fine.

**Comment by IotaBread** [comment]
I have identified the issue: Modrinth is picking up the sources jar instead of the distribution jar and it wont let me change or delete it. I'll get in contact with them asap

**Comment by IotaBread** [comment]
I have opened an issue at the Modrinth web page repository, once it gets fixed I will fix this

**Comment by IotaBread** [comment]
I forgot to close this. It has been fixed
