### ISSUE TITLE
Multithreaded downloads

### ISSUE THREAD

**Issue by solonovamax** [ByMartrixx/VTDownloader#5]
Pretty simple. Use multiple threads to speed up many downloads.
I have quite a lot of download speed, and I'd really appreciate being able to use that to speed up launch.
(Might pr it if I get a chance)

**Comment by solonovamax** [comment]
oops, opened this on the wrong gh LMFAO.

I thought this was a gh for another mod.

**Comment by IotaBread** [comment]
No worries
